site_name: goprohero
# docs_dir: './'
theme: readthedocs
# use_directory_urls: false
repo_url: https://github.com/joshvillbrandt/goprohero
markdown_extensions: ['tables']
pages:
- ['index.md', 'Home']
- ['Setup.md', 'User Guide', 'Setup']
- ['API.md', 'API']
- ['Command Line Interface.md', 'Command Line Interface']
- ['GoPro Firmware Instructions.md', 'GoPro Firmware Instructions']
- ['Wifi Research.md', 'Wifi Research']
- ['Change History.md', 'Change History']
